x-minio-common: &minio-common
  image: minio/minio:RELEASE.2023-03-09T23-16-13Z
  container_name: minio1_container_202
  command: server --console-address ":9001" http://minio1/data{1...2}
  ports:
    - "9000:9000"
    - "9001:9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MINIO_PROMETHEUS_AUTH_TYPE: public
    MINIO_SERVER_URL: "https://minio.deepbim.net:9000"           # public endpoint cho API
    MINIO_BROWSER_REDIRECT_URL: https://minio.deepbim.net:9443 # public endpoint cho web console
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "https://minio.deepbim.net:9000/minio/health/live"]
  #   interval: 30s
  #   timeout: 20s
  #   retries: 3
  # networks:
  #   - prod_backend_network

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "9000:9000"   # Proxy API S3 ra ngoài
      - "9443:443"    # Proxy Console web ra ngoài
      - "8070:80"
    depends_on:
      - minio1
    networks:
    - prod_backend_network

volumes:
  data1-1:
  data1-2:

networks:
  prod_backend_network:
    external: true
    name: prod_backend_network