services:
  minio1:
    image: minio/minio:RELEASE.2024-06-29T01-20-47Z
    command: server --console-address ":9001" http://minio1/data{1...2}
    hostname: minio1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SERVER_URL: https://minio.deepbim.net
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    expose:
      - "9000"
      - "9001"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - minio1

volumes:
  data1-1:
  data1-2:
